# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default_twitter: &default_twitter
  twitter_api_key: 'UBNCywiHlUPoZq1IspbuAD2pe'
  twitter_api_secret: 'V2REYgAXG7LizDjr7zgd1i0pdAkRWwPjR2DKNFaYbRuHhRzTFz'

development:
  secret_key_base: 524804f417fac16766bf79c858aecc2bdc88e26e0325791f434b2a0b8aae5dd026fdb20022b667eb8026d04d34d9dc898f7ab53ae6a0cf3710aebbbe372558a9
  <<: *default_twitter

test:
  secret_key_base: ba504f0e3ebbe1e5692a5f2e06ca6df2b8e79c198250326e0e23be953099a0aad0e2d14c52e2d063452bce68e8224d325f9a34a9bd580d7858fb6bed9c2a96ab
  <<: *default_twitter

    # Do not keep production secrets in the repository,
    # instead read values from the environment.
  production:
    secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_api_secret: <% ENV["TWITTER_CONSUMER_SECRET"] %>
